### ISSUE TITLE
What do these errors mean and how to fix them?

### ISSUE THREAD

**Issue by Tarkiin** [Discord-Token/Discord-token-generatorPY#12]
[-] Captcha on email verify, retrying!

[-] Error: 'NoneType' object has no attribute 'encode'
{"captcha_key": ["sitekey-secret-mismatch"], "captcha_sitekey": "", "captcha_service": "hcaptcha"}

Thanks!

![image](https://user-images.githubusercontent.com/61888270/149662531-0df0b475-de25-426a-99fe-78eea893b498.png)

**Comment by EmilMihaylov** [comment]
I see same errors...

**Comment by ItsChasa** [comment]
it means that ur captcha is bad

**Comment by rikuru-to865** [comment]
how....

**Comment by marconovino** [comment]
same error using anti-captcha

**Comment by itschasa** [comment]
> same error using anti-captcha

bro you guys haven't even noticed, discord changed their hcaptcha site key lmfao
