### ISSUE TITLE
token generated was locked

### ISSUE THREAD

**Issue by kcinnaydev** [Discord-Token/Discord-token-generatorPY#3]
token generated was locked

**Comment by oAaronn** [comment]
boo hoo

**Comment by oxitheman** [comment]
what

**Comment by FreeMoneyHyb** [comment]
n

**Comment by cliphd** [comment]
its a free gen

**Comment by oxitheman** [comment]
> its a free gen 

And? It works![IMG_20220116_101828_968.jpg](https://user-images.githubusercontent.com/70095434/149647667-02987084-00d4-48c7-ba1d-7b94b3bbc288.jpg)

**Comment by oxitheman** [comment]
You just need a brain and 15 minutes of time to make it work. This gen made me thousands of dollars selling tokens before i released it haha.
