### ISSUE TITLE
When using proxies I get this error [Errno 10061] No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by kcinnaydev** [Discord-Token/Discord-token-generatorPY#4]
When using proxies I get this error [Errno 10061] No connection could be made because the target machine actively refused it

**Comment by ufkundou** [comment]
same

**Comment by dcprem** [comment]
same

**Comment by srs775** [comment]
I'm getting the same error aswell

**Comment by oxitheman** [comment]
auth the proxies to your ip

**Comment by dcprem** [comment]
it shows raw_items not found in list smh
