### ISSUE TITLE
stop

### ISSUE THREAD

**Issue by ghost** [Discord-Token/Discord-token-generatorPY#8]
stop leaking free gens to the skids i just wanna generate myself now on my gen but u guys are using all of anti captcha indian workers bro

**Comment by eric48906** [comment]
don't act like you're not one of them

**Comment by qizq1337** [comment]
> don't act like you're not one of them 

i'm not LOL i'm using my own generator why would i use this gen 🤣🤣🤣

**Comment by eric48906** [comment]
Buddy you are a skid

**Comment by qizq1337** [comment]
> Buddy you are a skid

im not eric
